-- =================
-- Create tables
-- ================

CREATE TABLE "roles" (
 "id" INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
 "name" VARCHAR(50) NOT NULL
);

CREATE TABLE "users" (
    "id" VARCHAR(100) NOT NULL PRIMARY KEY,
    "username" VARCHAR(50) NOT NULL,
    "email" VARCHAR(100) NOT NULL,
    "password" VARCHAR(100) NOT NULL,
    "image_url" VARCHAR (250),
    "role_id" INT NOT NULL references "roles" (id),
    "register_datetime" TIMESTAMP NOT NULL
);

CREATE TABLE "posts" (
    "id" INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "video_url" VARCHAR (255) NOT NULL,
    "description" VARCHAR (255),
    "user_id" VARCHAR(255) NOT NULL references "users" (id) ON DELETE CASCADE ON UPDATE CASCADE,
    "datetime" TIMESTAMP NOT NULL
);

CREATE TABLE "comments" (
    "id" INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "comment" VARCHAR (500),
    "user_id" VARCHAR(255) NOT NULL references "users" (id) ON DELETE CASCADE ON UPDATE CASCADE,
    "post_id" INT NOT NULL references "posts" (id) ON DELETE CASCADE ON UPDATE CASCADE,
    "datetime" TIMESTAMP NOT NULL
);

-- =================
-- Init table values
-- ================
-- Init roles values

INSERT INTO "roles" (id, name) VALUES (1, 'ADMIN');
INSERT INTO "roles" (id, name) VALUES (2, 'USER');

-- Init users values
INSERT INTO "users" (id, username, email, password, role_id, register_datetime)
VALUES ('71af9941-45df-4cdf-bec2-934dc8e1c513', 'dino', 'dino7dujmovic@gmail.com', '$2b$10$F9agBAmE4LM/HbnJgcOU9umksdeYXnSCOdWACiF2afhm0/qUje2Qa', 1, CURRENT_TIMESTAMP);
